name: 'Generate the SAMQuote Version number'
description: 'Get started with Node actions'
author: 'GitHub'
inputs:
  majeure:
    description: 'Majeure version number'
    default: 'v19-08'
runs:
  using: 'node12'
  main: 'lib/main.js'